name = "Locks"
uuid = "b2b8d39d-860c-47cc-b75e-a6e39294eaae"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
ExternalDocstrings = "e189563c-0753-4f5e-ad5c-be4293c83fb4"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Try = "bf1d0ff0-c4a9-496b-85f0-2b0d71c4f32a"

[compat]
julia = "1.6"
